### ISSUE TITLE
How can I configure ignores for specific tests

### ISSUE THREAD

**Issue by bararchy** [veelenga/vscode-crystal-ameba#1]

**Comment by veelenga** [comment]
The plugin doesn't take into account `.ameba.yml` file, but it should.

Will that solve your issue?

**Comment by bararchy** [comment]
yeha :) then I can configure in the file which things to ignore, that will fix my issue.

**Comment by veelenga** [comment]
Just published v0.0.2 which includes the fix.

https://marketplace.visualstudio.com/items?itemName=veelenga.crystal-ameba
