### ISSUE TITLE
Unable to install, there is no available version compatible with VS Code '1.22.2'

### ISSUE THREAD

**Issue by Alastair-smith2** [veelenga/vscode-crystal-ameba#2]
Thanks for the time you've put towards a linter for Crystal!

The issue I'm having is in the title, can't get this plugin to work with the described version. Is there a minimum version of vscode required? (just seen the latest version of vscode is 1.32, will try and update if not)

I'm able to install ameba via home-brew and is working from the command line correctly 👍 

Environment 
Crystal Version 0.27.2
OSX Version Mojave 10.14

**Comment by veelenga** [comment]
Yeah, I used 1.32 to develop the plugin.

Will try to decrease the version to oldest compatible.

**Comment by veelenga** [comment]
Just published the ext built with 1.22.0 engine
