### ISSUE TITLE
Very liberal with the color underlining, problem level also questionable

### ISSUE THREAD

**Issue by taylorthurlow** [veelenga/vscode-crystal-ameba#3]
Here's a photo:

![Screen Shot 2019-06-06 at 10 42 59 PM](https://user-images.githubusercontent.com/761640/59083508-7a5a4700-88ac-11e9-8d6e-72c9f7130e2f.png)

All of this highlighting is because the cyclomatic complexity warning. I think two things should be changed:
- The only underlined part should be the method definition/signature, not the entire body of the method
- It should not be underlined in red, because it is not an error - typically linter suggestions like this would be done in a green underline. I assume this is because right now it's logged as an "error" and not a linter suggestion.

**Comment by veelenga** [comment]
@taylorthurlow yes, this is a bug. Both of your suggestions are correct.

**Comment by iambudi** [comment]
Currently i need to disable the vscode extension to avoid the red underlined error and do manually run ameba from console. Hopefully there's a fix near soon. Thank you.

**Comment by veelenga** [comment]
The first part of this issue is fixed by https://github.com/veelenga/ameba/commit/b868d88a850e96e80ce5185f3ec5d6e2bc8598e0

![image](https://user-images.githubusercontent.com/3624712/61157333-84501500-a4fe-11e9-97b6-22b713095e6f.png)

**Comment by veelenga** [comment]
Now severity is populated to the extension:

![image](https://user-images.githubusercontent.com/3624712/61160306-a7cb8d80-a507-11e9-8fcc-bc5c74af5502.png)
